let date1 = new Date()
let date2 = new Date("09/08/1998")
let difference =(date1.getTime()-date2.getTime())/(1000*60*60*24*365)
console.log(Math.floor(difference))
console.log(Math.ceil(difference))
// console.log(date.toLocaleDateString())
// console.log(date.toLocaleTimeString())
// console.log(date.toLocaleString())
// console.log(date.getTime())
// console.log(date.getFullYear())
// console.log(date.getDay())
// console.log(date.getMonth())
// console.log(date.getMinutes())
// date.setFullYear("2023")
// console.log(date)