var os = require("os")
console.log(os)
console.log("CPU Architechture : "+ os.arch())
console.log("Free Memory :"+ os.freemem())
const memory = (os.freemem()/(1024*1024*1024))
console.log(memory)
const totalMemory = (os.totalmem()/(1024*1024*1024))
console.log(totalMemory)
console.log("Host Name : "+os.hostname())
console.log("Operating Name : ", os.type())
console.log("os platform :", os.platform())
console.log("os release :", os.release())