var students = [{
    "id": 1,
    "first_name": "Paten",
    "last_name": "Atterley",
    "email": "patterley0@si.edu"
  }, {
    "id": 2,
    "first_name": "Cloris",
    "last_name": "Ely",
    "email": "cely1@sourceforge.net"
  }, {
    "id": 3,
    "first_name": "Katrine",
    "last_name": "Joerning",
    "email": "kjoerning2@foxnews.com"
  }, {
    "id": 4,
    "first_name": "Leila",
    "last_name": "Grimston",
    "email": "lgrimston3@samsung.com"
  }, {
    "id": 5,
    "first_name": "Diena",
    "last_name": "Ewbanks",
    "email": "dewbanks4@usnews.com"
  }, {
    "id": 6,
    "first_name": "Izzy",
    "last_name": "Woodbridge",
    "email": "iwoodbridge5@webs.com"
  }, {
    "id": 7,
    "first_name": "Dexter",
    "last_name": "Rae",
    "email": "drae6@mysql.com"
  }, {
    "id": 8,
    "first_name": "Elsinore",
    "last_name": "Stutter",
    "email": "estutter7@spiegel.de"
  }, {
    "id": 9,
    "first_name": "Luce",
    "last_name": "Belshaw",
    "email": "lbelshaw8@nifty.com"
  }, {
    "id": 10,
    "first_name": "Ross",
    "last_name": "Kirlin",
    "email": "rkirlin9@go.com"
  }]
  module.exports = students