var fs = require("fs")
console.log(fs)
// fs.writeFileSync("./adfar.txt"," node js file module today")
// fs.writeFileSync("./index.html","<h1>Starting node js file module today</h1>")
// const data = fs.readFileSync("./index.html","utf-8")
// // console.log(data.toString())
// console.log(data)
// fs.appendFileSync("Ishan.txt"," and we have only 9 days left")
// fs.unlinkSync("./file")
// fs.rmdirSync("./file")
fs.renameSync("Ishan.txt","lpu.txt")